language: ruby

sudo: false

rvm:
  - 2.3.3

before_install:
  - "rm Gemfile.lock"
  - "gem update --system"
  - "gem update bundler"

script:
  - export RAILS_ENV=test
  - bundle exec rspec ./spec --color --format documentation --require spec_helper --require rails_helper
